_wandb:
    value:
        cli_version: 0.22.2
        e:
            3h11vulb408m3qn0wv9l9d5opcy5py1p:
                codePath: training_example.py
                codePathLocal: training_example.py
                email: aaditya@architectchips.com
                executable: /Users/aadityasubedi/Desktop/tinker/tinker-cookbook/venv/bin/python
                git:
                    commit: 1cbb08330370542e0b055f636dbab1579a5499d8
                    remote: git@github.com:thinking-machines-lab/tinker-cookbook.git
                host: Aadityas-MacBook-Pro.local
                os: macOS-14.6.1-arm64-arm-64bit
                program: /Users/aadityasubedi/Desktop/tinker/tinker-cookbook/training_example.py
                python: CPython 3.12.9
                root: /Users/aadityasubedi/Desktop/tinker/tinker-cookbook/training_logs/run_3
                startedAt: "2025-10-22T17:19:35.284553Z"
                writerId: 3h11vulb408m3qn0wv9l9d5opcy5py1p
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 13
                - 16
            "4": 3.12.9
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.95
adam_eps:
    value: 1e-08
base_url:
    value: null
dataset_builder:
    value:
        common_config:
            batch_size: 8
            max_length: 2048
            model_name_for_tokenizer: meta-llama/Llama-3.2-1B
            renderer_name: role_colon
            train_on_what: ALL_ASSISTANT_MESSAGES
        file_path: example-data/conversations.jsonl
        shuffle_seed: 42
        test_size: 24
eval_every:
    value: 10
evaluator_builders:
    value: []
infrequent_eval_every:
    value: 100
infrequent_evaluator_builders:
    value: []
learning_rate:
    value: 0.0005
load_checkpoint_path:
    value: null
log_path:
    value: /Users/aadityasubedi/Desktop/tinker/tinker-cookbook/training_logs/run_3
lora_rank:
    value: 32
lr_schedule:
    value: linear
model_name:
    value: meta-llama/Llama-3.2-1B
num_epochs:
    value: 3
save_every:
    value: 10
wandb_name:
    value: training-example
wandb_project:
    value: tinker-SFT
